swagger: '2.0'
info:
  title: Momentum
  version: '1.0.0'
basePath: /worker
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:

  /hb:
    get:
      x-swagger-router-controller: "hb"
      responses:
        200:
          description: successful response
  /rules:
    get:
      x-swagger-router-controller: "rules"
      responses:
        200:
          description: successful response
  /crawler:
    get:
      x-swagger-router-controller: "crawler"
      responses:
        200:
          description: successful response
